[package]
edition = "2018"
name = "lucifer-ui"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ybc = "0.2.1"
yew = "0.18"
